"""update migrations

Revision ID: 0024b262c32f
Revises: 47f1bed3d7fd
Create Date: 2022-07-04 18:28:22.833619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0024b262c32f'
down_revision = '47f1bed3d7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
