"""update migrations

Revision ID: 068cb4150d2c
Revises: 7bdc1398411f
Create Date: 2022-07-04 05:43:41.775569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068cb4150d2c'
down_revision = '7bdc1398411f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
