"""update migrations

Revision ID: 088eeccc41d5
Revises: dc34da100270
Create Date: 2022-07-04 19:04:17.098752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088eeccc41d5'
down_revision = 'dc34da100270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
