"""update migrations

Revision ID: 0cdb34667a49
Revises: 0e6192485cb7
Create Date: 2022-07-04 04:11:01.585833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdb34667a49'
down_revision = '0e6192485cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
