"""update migrations

Revision ID: 0e6192485cb7
Revises: b394289b7b52
Create Date: 2022-07-04 04:05:53.517332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6192485cb7'
down_revision = 'b394289b7b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
