"""update migrations

Revision ID: 17e38b242da0
Revises: 6c795ec5d26b
Create Date: 2022-07-04 06:08:15.714249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e38b242da0'
down_revision = '6c795ec5d26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
