"""update migrations

Revision ID: 47f1bed3d7fd
Revises: 17e38b242da0
Create Date: 2022-07-04 18:26:35.404161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f1bed3d7fd'
down_revision = '17e38b242da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'image')
    # ### end Alembic commands ###
