"""update migrations

Revision ID: 4aad23d822f9
Revises: 0cdb34667a49
Create Date: 2022-07-04 04:13:54.841979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aad23d822f9'
down_revision = '0cdb34667a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
