"""update migrations

Revision ID: 517d2dbddfce
Revises: 67cf9fe6e439
Create Date: 2022-07-04 01:16:35.701506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "517d2dbddfce"
down_revision = "67cf9fe6e439"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("gender", sa.Enum("Male", "Female", name="gender"), nullable=True),
        sa.Column("birth_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_full_name"), "patient", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_patient_id"), "patient", ["id"], unique=False)
    op.create_table(
        "case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "diagnostic",
            sa.Enum(
                "COVID19",
                "Influenza",
                "CommonCold",
                "Tuberculosis",
                "LungCancer",
                "PneumoniaCOVID19",
                "Pneumonia",
                "BrainTumor",
                name="diagnostic",
            ),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_case_id"), "case", ["id"], unique=False)
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "symptom",
            sa.Enum(
                "Fever",
                "DryCough",
                "Rhinorrhea",
                "Dyspnea",
                "Fatigue",
                "MusclePain",
                "ChestPain",
                "Anosmia",
                "Dysgeusia",
                "KidneyFailure",
                "Myocarditis",
                "Hemoptisis",
                "Headache",
                name="symptom",
            ),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_history_id"), "history", ["id"], unique=False)
    op.drop_index("ix_item_description", table_name="item")
    op.drop_index("ix_item_id", table_name="item")
    op.drop_index("ix_item_title", table_name="item")
    op.drop_table("item")
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "item",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="item_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="item_pkey"),
    )
    op.create_index("ix_item_title", "item", ["title"], unique=False)
    op.create_index("ix_item_id", "item", ["id"], unique=False)
    op.create_index("ix_item_description", "item", ["description"], unique=False)
    op.drop_index(op.f("ix_history_id"), table_name="history")
    op.drop_table("history")
    op.drop_index(op.f("ix_case_id"), table_name="case")
    op.drop_table("case")
    op.drop_index(op.f("ix_patient_id"), table_name="patient")
    op.drop_index(op.f("ix_patient_full_name"), table_name="patient")
    op.drop_table("patient")
    # ### end Alembic commands ###
