"""update migrations

Revision ID: 530ee56b9a0e
Revises: c4c11e4a8d0d
Create Date: 2022-07-04 05:36:48.858708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530ee56b9a0e'
down_revision = 'c4c11e4a8d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
