"""update migrations

Revision ID: 6c795ec5d26b
Revises: 911f590d6ff8
Create Date: 2022-07-04 06:04:34.625090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c795ec5d26b'
down_revision = '911f590d6ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'state')
    # ### end Alembic commands ###
