"""update migrations

Revision ID: 6eaf42c7299a
Revises: 530ee56b9a0e
Create Date: 2022-07-04 05:39:30.808384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaf42c7299a'
down_revision = '530ee56b9a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
