"""update migrations

Revision ID: 77a12225a0ea
Revises: 7d01483c770c
Create Date: 2022-07-04 02:45:17.150914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77a12225a0ea"
down_revision = "7d01483c770c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
