"""update migrations

Revision ID: 7bdc1398411f
Revises: 6eaf42c7299a
Create Date: 2022-07-04 05:42:26.335826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdc1398411f'
down_revision = '6eaf42c7299a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
