"""update migrations

Revision ID: 7d01483c770c
Revises: 9f5d19471ce5
Create Date: 2022-07-04 02:44:34.466028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d01483c770c"
down_revision = "9f5d19471ce5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
