"""update migrations

Revision ID: 999d9b534ecd
Revises: 4aad23d822f9
Create Date: 2022-07-04 04:17:44.599242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999d9b534ecd'
down_revision = '4aad23d822f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
