"""update migrations

Revision ID: 9f5d19471ce5
Revises: 517d2dbddfce
Create Date: 2022-07-04 01:40:17.865995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f5d19471ce5"
down_revision = "517d2dbddfce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patient", sa.Column("code", sa.String(), nullable=True))
    op.create_index(op.f("ix_patient_code"), "patient", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patient_code"), table_name="patient")
    op.drop_column("patient", "code")
    # ### end Alembic commands ###
