"""update migrations

Revision ID: b394289b7b52
Revises: 42045dc7870b
Create Date: 2022-07-04 04:03:45.102841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b394289b7b52'
down_revision = '42045dc7870b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
