"""update migrations

Revision ID: b71e82dc50ee
Revises: 068cb4150d2c
Create Date: 2022-07-04 05:45:12.434293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71e82dc50ee'
down_revision = '068cb4150d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
