"""update migrations

Revision ID: c2712758220a
Revises: 77a12225a0ea
Create Date: 2022-07-04 03:53:15.796276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2712758220a'
down_revision = '77a12225a0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
