"""update migrations

Revision ID: c4c11e4a8d0d
Revises: 999d9b534ecd
Create Date: 2022-07-04 05:20:34.819617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c11e4a8d0d'
down_revision = '999d9b534ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
