"""update migrations

Revision ID: e27b77c3abc7
Revises: b71e82dc50ee
Create Date: 2022-07-04 05:46:42.410439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27b77c3abc7'
down_revision = 'b71e82dc50ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
